// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolApi.Data;

#nullable disable

namespace SchoolApi.Data.Migrations
{
    [DbContext(typeof(SchoolDbContext))]
    partial class SchoolDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.12");

            modelBuilder.Entity("SchoolLibrary.Student", b =>
                {
                    b.Property<string>("StudentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("School")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("StudentId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = "ba84a096-0b66-4f9f-98c0-fb6adcb97df2",
                            FirstName = "Tom",
                            LastName = "Day",
                            School = "Physics"
                        },
                        new
                        {
                            StudentId = "b7ff0d21-95ce-4eb2-8b8e-cd4d59c35a25",
                            FirstName = "Ann",
                            LastName = "Fox",
                            School = "Geology"
                        },
                        new
                        {
                            StudentId = "0a1e4bcc-7e33-4582-8b72-6f755b5c7f07",
                            FirstName = "Art",
                            LastName = "Ash",
                            School = "Nursing"
                        },
                        new
                        {
                            StudentId = "e95f565f-ae45-4b4b-8720-6b75baea3a2d",
                            FirstName = "Mia",
                            LastName = "Hay",
                            School = "Science"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
